export const PRICE_CATALOG = {
  basic: [
    {
      name: 'Basic',
      price: 49000,
      feature: [
        'Link Unik',
        'Responsive',
        'Nama Tamu Undangan',
        'Unlimited Share',
        'Masa Aktif 1 Bulan',
        'Informasi Pengantin',
        'Countdown Waktu',
        'Petunjuk Lokasi',
        'Peraturan Khusus',
        'Kutipan Ayat/Sastra',
        'Pesan Penutup',
      ],
      earlyPrice: 98000,
      message: 'Potongan 50%',
    },
  ],
  special: [
    {
      name: 'Special',
      price: 59000,
      feature: [
        <span className="font-bold">Semua Fitur Basic</span>,
        'Background Musik',
        'Masa Aktif 3 Bulan',
        '1 Kutipan Ayat/Sastra',
        '3 Foto Galeri',
        'Cerita Singkat',
        'Ucapan dan Doa',
        'Gift 2 Metode',
        'RSVP',
      ],
      earlyPrice: 118000,
      message: 'Potongan 50%',
    },
    {
      name: 'Special+',
      price: 89000,
      feature: [
        <span className="font-bold">Semua Fitur Basic</span>,
        <span className="font-bold">Custom Background Music</span>,
        <span className="font-bold">Masa Aktif 9 Bulan</span>,
        <span className="font-bold">3 Kutipan Ayat/Sastra</span>,
        <span className="font-bold">6 Foto & 1 Video di Galeri</span>,
        'Cerita Singkat',
        'Ucapan dan Doa',
        'Gift 2 Metode',
        'RSVP',
        <span className="font-bold">Custom Font & Warna</span>,
        // <span className="font-bold">Button Menu</span>,
      ],
      earlyPrice: 178000,
      message: 'Potongan 50%',
    },
  ],
  premium: [
    {
      name: 'Premium',
      price: 79000,
      feature: [
        <span className="font-bold">Semua Fitur Special</span>,
        'Background Musik',
        'Masa Aktif 3 Bulan',
        '1 Kutipan Ayat/Sastra',
        '3 Foto Galeri',
        'Gift 5 Metode',
        'Milestone',
        'Rundown Acara',
        'RSVP Kedua Mempelai',
        'Our Bestfriends',
        'Wedding Journal',
      ],
      earlyPrice: 158000,
      message: 'Potongan 50%',
    },
    {
      name: 'Premium+',
      price: 109000,
      feature: [
        <span className="font-bold">Semua Fitur Special</span>,
        <span className="font-bold">Custom Background Music</span>,
        <span className="font-bold">Masa Aktif 9 Bulan</span>,
        <span className="font-bold">3 Kutipan Ayat/Sastra</span>,
        <span className="font-bold">6 Foto & 1 Video di Galeri</span>,
        'Gift 5 Metode',
        'Milestone',
        'Rundown Acara',
        'RSVP Kedua Mempelai',
        'Our Bestfriends',
        'Wedding Journal',
        <span className="font-bold">Custom Font & Warna</span>,
        <span className="font-bold">Button Menu</span>,
      ],
      earlyPrice: 218000,
      message: 'Potongan 50%',
    },
  ],
}

export const EIDMUBARAK = {
  package: {
    name: 'Pre Order Idul Fitri',
    price: 10000,
    feature: [
      'Link Unik',
      'Unlimited Share',
      'Desain Menarik',
      'Nama Penerima',
      'Foto Keluarga',
      'Pesan Khusus',
    ],
    earlyPrice: 25000,
    message: 'Promo Pre Order hingga 28 April 2022',
  },
  topping: [
    {
      name: 'Kutipan Tambahan',
      price: 0,
      desc: 'Tampilkan kutipan Surat atau Hadist bahasa indonesia',
      earlyPrice: 2000,
    },
    {
      name: 'Foto Tambahan',
      price: 2000,
      desc: 'Tampilkan 3 foto di kartu ucapan',
      earlyPrice: 4000,
    },
    {
      name: 'Ucapan Balik',
      price: 5000,
      desc: 'Penerima dapat mengirim ucapan balasan yang diteruskan ke WhatApp',
      earlyPrice: 10000,
    },
    {
      name: 'E-THR',
      price: 5000,
      desc: 'Tampilkan informasi pembayaran biar dikirimin THR Online',
      earlyPrice: 10000,
    },
    {
      name: 'Galeri Video',
      price: 5000,
      desc: 'Tampilkan video ucapan idul fitri di kartu uncapan',
      earlyPrice: 10000,
    },
    {
      name: 'Tambah Musik',
      price: 2000,
      desc: 'Putar musik atau audio lain di kartu ucapanmu',
      earlyPrice: 4000,
    },
    {
      name: 'Custom Warna & Font',
      price: 8000,
      desc: 'Ubah warna dan font kartu ucapan sesuai request',
      earlyPrice: 16000,
    },
    {
      name: 'Masa Aktif Lebih',
      price: 5000,
      desc: 'Kartu Ucapan mu dapat dilihat lebih lama hingga 7 Syawal 1443H',
      earlyPrice: 10000,
    },
    {
      name: 'Isi Nama Penerima',
      price: 10000,
      desc: 'Kami bantu isi nama penerima custom hingga 10 orang',
      earlyPrice: 20000,
    },
    {
      name: 'Semua Topping',
      price: 30000,
      desc: 'Beli semua Topping (kecuali custom warna dan font) lebih murah',
      earlyPrice: 68000,
    },
  ],
}

export const TOPPING_CATALOG = [
  {
    name: 'Kutipan Tambahan',
    price: 2000,
    desc: 'Nampilin kutipan ayat atau kata kata mutiara lebih banyak',
    earlyPrice: 4000,
  },
  {
    name: 'Masa Aktif Selamanya',
    price: 80000,
    desc: 'Bisa buka undangan kapan aja, biar bisa nostalgia',
    earlyPrice: 160000,
  },
  {
    name: 'Galeri Pasca Wedding',
    price: 20000,
    desc: 'Bagikan foto foto setelah acara',
    earlyPrice: 40000,
  },
  {
    name: 'Filter Instagram',
    price: 20000,
    desc: 'Bagikan foto foto setelah acara',
    earlyPrice: 40000,
  },
  {
    name: 'Opening Video',
    price: 20000,
    desc: 'Bagikan foto foto setelah acara',
    earlyPrice: 40000,
  },
]
